/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "reverse_long_tests.ts" instead.
 */

#include <check.h>

#line 1 "reverse_long_tests.ts"
#include "reverse.h"
#include <stdlib.h>

START_TEST(reverse_long)
{
#line 5
    size_t count = 10000000;
    // Allocate memory for 10 million integers
    int *array = malloc(sizeof(int) * count);
    int *reversed = malloc(sizeof(int) * count);

    for (size_t i = 0; i < count; i++){
        array[i] = i;
        reversed[i] = count - 1 - i;
    }

    // Reverse 10 million values
    reverse(array, count, 0, count);

    // Check if arrays are equal
    for (size_t i = 0; i < count; i++){
        if (array[i] != reversed[i]){
            ck_assert_int_eq(array[i], reversed[i]);
        }
    }

    // Free memory
    free(array);
    free(reversed);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, reverse_long);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
