/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "reverse_tests.ts" instead.
 */

#include <check.h>

#line 1 "reverse_tests.ts"
#include "reverse.h"
#include <stdint.h>

// In dieser Datei müssen weitere Tests implementiert werden.

START_TEST(reverse_1234)
{
#line 7
	int array[4] = {1, 2, 3, 4};
	int reversed[4] = {4, 3, 2, 1};

	// Reverse the array
	reverse(array, 4, 0, 4);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(reverse_12345)
{
#line 19
	int array[5] = {1, 2, 3, 4, 5};
	int reversed[5] = {4, 3, 2, 1, 5};

	// Reverse the array
	reverse(array, 5, 0, 4);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 5; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}


}
END_TEST

START_TEST(reverse_12345_All_5)
{
#line 32
	int array[5] = {1, 2, 3, 4, 5};
	int reversed[5] = {5, 4, 3, 2, 1};

	// Reverse the array
	reverse(array, 5, 0, 5);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 5; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}


}
END_TEST

START_TEST(reverse_subrange2)
{
#line 45
	int array[7] = {3, 4, 8, 2, 7, 1, 5};
	int reversed[7] = {3, 4, 1, 7, 2, 8, 5};

	// Reverse 4 values starting at index 2
	reverse(array, 7, 2, 4);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 7; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}


}
END_TEST

START_TEST(reverse_1221)
{
#line 58
	int array[4] = {1, 2, 2, 1};
	int reversed[4] = {1, 2, 2, 1};

	// Reverse the array
	reverse(array, 4, 0, 4);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(reverse_subrange)
{
#line 70
	int array[7] = {3, 4, 1, 2, 2, 1, 5};
	int reversed[7] = {3, 4, 1, 2, 2, 1, 5};

	// Reverse 4 values starting at index 2
	reverse(array, 4, 2, 4);

	// Check if the array is now equal to the reversed array
	for (size_t i = 0; i < 7; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(reverse_invalid_count_too_large)
{
#line 82
	int array[4] = {1, 2, 3, 4};
	int reversed[4] = {1, 2, 3, 4};

	reverse(array, 4, 0, 5);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(reverse_length_too_small)
{
#line 92
	reverse(NULL, 0, 0, 0);

}
END_TEST

START_TEST(invalid_count_too_small)
{
#line 95
	int array[4] = {1, 2, 3, 4};
	int reversed[4] = {1, 2, 3, 4};

	reverse(array, 4, 5, 0);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 5, 1);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(invalid_index_too_large)
{
#line 111
	int array[4] = {1, 2, 3, 4};
	int reversed[4] = {1, 2, 3, 4};

	reverse(array, 4, 5, 2);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 99999999, 0);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 99999999, 1);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

}
END_TEST

START_TEST(invalid_index_plus_count_too_large)
{
#line 133
	int array[4] = {1, 2, 3, 4};
	int reversed[4] = {1, 2, 3, 4};

	reverse(array, 4, 1, 4);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 2, 3);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 3, 2);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, 4, 1);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	// Might trigger integer overflow for size_t if not careful
	reverse(array, 4, SIZE_MAX / 2, SIZE_MAX / 2);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, SIZE_MAX / 2, SIZE_MAX / 2 + 1);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, SIZE_MAX / 2 + 1, SIZE_MAX / 2);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}

	reverse(array, 4, SIZE_MAX / 2 + 1, SIZE_MAX / 2 + 1);

	for (size_t i = 0; i < 4; i++){
		ck_assert_int_eq(array[i], reversed[i]);
	}
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, reverse_1234);
    tcase_add_test(tc1_1, reverse_12345);
    tcase_add_test(tc1_1, reverse_12345_All_5);
    tcase_add_test(tc1_1, reverse_subrange2);
    tcase_add_test(tc1_1, reverse_1221);
    tcase_add_test(tc1_1, reverse_subrange);
    tcase_add_test(tc1_1, reverse_invalid_count_too_large);
    tcase_add_test(tc1_1, reverse_length_too_small);
    tcase_add_test(tc1_1, invalid_count_too_small);
    tcase_add_test(tc1_1, invalid_index_too_large);
    tcase_add_test(tc1_1, invalid_index_plus_count_too_large);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
